version: '2'
services:
    hopejustfound-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/hopeJustFound/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=hopeJustFound
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
